include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - 'vendor/pub-cache/**'
    - '**/vendor/pub-cache/**'

linter:
  rules:
    # Formatting-related rules
    lines_longer_than_80_chars: false  # Allow longer lines
    prefer_single_quotes: true

    # Style rules
    require_trailing_commas: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
