const fs = require('fs');
const path = require('path');

// Path to serverless.yml
const serverlessPath = path.resolve(__dirname, '..', 'packages', 'aws_backend', 'serverless.yml');
const outDartPath = path.resolve(__dirname, '..', 'packages', 'sltt_core', 'lib', 'src', 'server', 'server_urls.dart');

if (!fs.existsSync(serverlessPath)) {
  console.error('serverless.yml not found at', serverlessPath);
  process.exit(2);
}

const yamlText = fs.readFileSync(serverlessPath, 'utf8');

// Heuristic: extract region and stage then construct the API Gateway base URL.
// Serverless does not include the REST API id directly in serverless.yml. If you
// deploy with the Serverless Framework, the deployed API URL typically looks like:
// https://{restApiId}.execute-api.{region}.amazonaws.com/{stage}
// We cannot infer restApiId from serverless.yml alone. We'll attempt to read an
// environment variable or a properties file named `.serverless/deploy-info.json` if present.

let region = 'us-east-1';
let stage = 'dev';

const regionMatch = yamlText.match(/region:\s*(\S+)/);
if (regionMatch) region = regionMatch[1].replace(/['"]/g, '');
const stageMatch = yamlText.match(/stage:\s*\$\{opt:stage,\s*'([^']+)'\}/) || yamlText.match(/stage:\s*\$\{opt:stage,\s*"([^"]+)"\}/) || yamlText.match(/stage:\s*(\S+)/);
if (stageMatch) {
  stage = stageMatch[1].replace(/['\"]+/g, '');
}

// Try reading .serverless/deploy-info.json
const deployInfoPath = path.resolve(__dirname, '..', 'packages', 'aws_backend', '.serverless', 'deploy-info.json');
let restApiId = null;
if (fs.existsSync(deployInfoPath)) {
  try {
    const deployInfo = JSON.parse(fs.readFileSync(deployInfoPath, 'utf8'));
    if (deployInfo.restApiId) restApiId = deployInfo.restApiId;
    // Some deployments may store outputs under `service` or `stack` keys
    if (!restApiId && deployInfo.service && deployInfo.service.restApiId) restApiId = deployInfo.service.restApiId;
  } catch (err) {
    // ignore
  }
}

// Fallback: check for an env var
if (!restApiId && process.env.SLTT_REST_API_ID) {
  restApiId = process.env.SLTT_REST_API_ID;
}

let cloudUrl = `https://${restApiId || 'REPLACE_ME'}.execute-api.${region}.amazonaws.com/${stage}`;

const dartContent = `// Cloud Dev URL for production AWS Lambda endpoint\n// Auto-generated by scripts/generate_server_urls.js\nconst String kCloudDevUrl =\n    '${cloudUrl}';\n`;

fs.writeFileSync(outDartPath, dartContent, 'utf8');
console.log('Wrote', outDartPath);
if (!restApiId) {
  console.warn('WARNING: restApiId not found. Please set SLTT_REST_API_ID env var or provide .serverless/deploy-info.json after deployment. The generated URL contains REPLACE_ME.');
}
