// Cloud Dev URL for production AWS Lambda endpoint
// Auto-generated by scripts/generate_server_urls.js
// Sourced from packages/aws_backend/.serverless/meta.json ServiceEndpoint
// (populated by Serverless Framework). If you re-deploy, re-run the
// generator script or set SLTT_REST_API_ID to regenerate this file.
const String kCloudDevUrl =
    'https://exz43jep09.execute-api.us-east-1.amazonaws.com/dev';
